namespace GamerBot_Budget.Commands;

internal sealed class Remind
{
    [Command("remind", "Reminds You Of Something", _Options: new string[] { "time", "message" })]
    public static async Task RemindCommand(SocketSlashCommand command)
    {
        //This entire command was generated by CoPilot, Like literally what the hell. minor adjustments but 95% was auto-generated

        var options = CommandHandler.GetCurrentOptions(command);
        var time = (options.ContainsKey("time") ? (string)options["time"] : null);
        var message = (options.ContainsKey("message") ? (string)options["message"] : null);

        if (time == null || message == null)
        {
            await command.RespondAsync("Please Provide A Time And A Message", ephemeral: true);
            return;
        }

        var parseSuccess = TimeSpan.TryParse(time,out var timeSpan);
        if (!parseSuccess)
        {
            await command.RespondAsync("Please Provide A Valid Time", ephemeral: true);
            return;
        }
        var remindTime = DateTime.Now + timeSpan;

        var reminder = new BackgroundChecks.Reminder(message, remindTime, command.User);
        BackgroundChecks.Reminders.Add(reminder);

        await command.RespondAsync($"I Will Remind You In {timeSpan.TotalMinutes} Minutes");
    }
}